# Generated by Django 5.0.9 on 2025-10-31 11:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('markdown', 1), ('code', 4), ('image', 7), ('quote', 8)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'template': 'blocks/heading_block.html'}), 1: ('wagtailmarkdown.blocks.MarkdownBlock', (), {'icon': 'pilcrow', 'template': 'blocks/markdown_block.html'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('bash', 'Bash/Shell'), ('html', 'HTML'), ('css', 'CSS'), ('sql', 'SQL'), ('json', 'JSON'), ('yaml', 'YAML'), ('dockerfile', 'Dockerfile')]}), 3: ('wagtail.blocks.TextBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('language', 2), ('code', 3)]], {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6), ('attribution', 6)]], {}), 8: ('wagtail.blocks.StructBlock', [[('quote', 3), ('author', 6)]], {})}),
        ),
    ]
