# Generated by Django 5.0.9 on 2025-10-31 13:11

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_blogpage_body'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(default='📁', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Project Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(default='⚙️', help_text='Emoji or icon', max_length=50)),
                ('color', models.CharField(default='#9fef00', help_text='Hex color for badge (e.g. #9fef00)', max_length=7)),
            ],
            options={
                'verbose_name': 'Tech Stack',
                'verbose_name_plural': 'Tech Stack',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Project date')),
                ('intro', models.CharField(help_text='Short description', max_length=250)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('archived', 'Archived'), ('ongoing', 'Ongoing')], default='completed', max_length=20)),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL')),
                ('live_url', models.URLField(blank=True, help_text='Live demo URL')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('markdown', 1), ('code', 4), ('image', 7), ('quote', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'template': 'blocks/heading_block.html'}), 1: ('wagtailmarkdown.blocks.MarkdownBlock', (), {'icon': 'pilcrow', 'template': 'blocks/markdown_block.html'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('bash', 'Bash/Shell'), ('html', 'HTML'), ('css', 'CSS'), ('sql', 'SQL'), ('json', 'JSON'), ('yaml', 'YAML'), ('dockerfile', 'Dockerfile')]}), 3: ('wagtail.blocks.TextBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('language', 2), ('code', 3)]], {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6), ('attribution', 6)]], {}), 8: ('wagtail.blocks.StructBlock', [[('quote', 3), ('author', 6)]], {})})),
                ('problem', wagtail.fields.RichTextField(blank=True, help_text='What problem did this solve?')),
                ('solution', wagtail.fields.RichTextField(blank=True, help_text='How did you solve it?')),
                ('duration', models.CharField(blank=True, help_text="e.g. '2 weeks', '3 months'", max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='home.projectcategory')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('tech_stack', models.ManyToManyField(blank=True, related_name='projects', to='home.techstack')),
            ],
            options={
                'verbose_name': 'Project',
                'ordering': ['-date'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
