# Generated by Django 5.0.9 on 2025-11-03 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contactpage_contactsubmission'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_in_navigation', models.BooleanField(default=True, help_text='Enable/disable automatic navigation')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Navigation Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter/X profile URL')),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('location', models.CharField(default='Stockholm, Sweden', help_text='Your location', max_length=100)),
                ('hackthebox_url', models.URLField(blank=True, help_text='HackTheBox profile URL')),
                ('tryhackme_url', models.URLField(blank=True, help_text='TryHackMe profile URL')),
                ('footer_text', models.CharField(default='Site Reliability Engineer | Security Enthusiast | HTB Player', help_text='Short bio for footer', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Social Media Settings',
            },
        ),
    ]
