# Generated by Django 5.0.9 on 2025-11-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_navigationsettings_socialmediasettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='htb_boxes_owned',
            field=models.IntegerField(default=0, help_text="Number of boxes you've owned"),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='htb_challenges',
            field=models.IntegerField(default=0, help_text='Challenges solved'),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='htb_rank',
            field=models.CharField(blank=True, default='Noob', help_text='Your HTB rank (e.g., Hacker, Pro Hacker, Elite)', max_length=50),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='htb_system_owns',
            field=models.IntegerField(default=0, help_text='System-owned flags'),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='htb_user_owns',
            field=models.IntegerField(default=0, help_text='User-owned flags'),
        ),
    ]
