# Generated by Django 5.0.9 on 2025-11-04 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_socialmediasettings_htb_boxes_owned_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Christian Bergane - Portfolio', help_text='Site name for meta tags', max_length=100)),
                ('meta_description', models.TextField(default='Site Reliability Engineer specializing in infrastructure, security, and automation. Based in Stockholm, Sweden.', help_text='Default meta description (max 160 characters)', max_length=160)),
                ('meta_keywords', models.CharField(default='SRE, DevOps, Security, Infrastructure, Django, Python, Proxmox', help_text='Default meta keywords (comma-separated)', max_length=255)),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics tracking ID (e.g., G-XXXXXXXXXX)', max_length=50)),
                ('og_image', models.ForeignKey(blank=True, help_text='Default Open Graph image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'SEO Settings',
            },
        ),
    ]
