# Generated by Django 5.1.3 on 2025-11-04 20:38

import django.db.models.deletion
import django.utils.timezone
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('icon', models.CharField(default='📝', help_text='Emoji or icon class', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Blog Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True, help_text='Text shown after successful submission')),
            ],
            options={
                'verbose_name': 'Contact Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('read', models.BooleanField(default=False)),
                ('replied', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Home Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(default='📁', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Project Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(default='⚙️', help_text='Emoji or icon', max_length=50)),
                ('color', models.CharField(default='#9fef00', help_text='Hex color for badge (e.g. #9fef00)', max_length=7)),
            ],
            options={
                'verbose_name': 'Tech Stack',
                'verbose_name_plural': 'Tech Stack',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Post date')),
                ('intro', models.CharField(help_text='Short intro (meta description)', max_length=250)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('markdown', 1), ('code', 4), ('image', 7), ('quote', 8)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'template': 'blocks/heading_block.html'}), 1: ('wagtailmarkdown.blocks.MarkdownBlock', (), {'icon': 'pilcrow', 'template': 'blocks/markdown_block.html'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('bash', 'Bash/Shell'), ('html', 'HTML'), ('css', 'CSS'), ('sql', 'SQL'), ('json', 'JSON'), ('yaml', 'YAML'), ('dockerfile', 'Dockerfile')]}), 3: ('wagtail.blocks.TextBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('language', 2), ('code', 3)]], {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6), ('attribution', 6)]], {}), 8: ('wagtail.blocks.StructBlock', [[('quote', 3), ('author', 6)]], {})})),
                ('reading_time', models.IntegerField(default=5, help_text='Minutes to read')),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='home.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'ordering': ['-date'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='home.blogpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.BlogPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_in_navigation', models.BooleanField(default=True, help_text='Enable/disable automatic navigation')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Navigation Settings',
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Christian Bergane - Portfolio', help_text='Site name for meta tags', max_length=100)),
                ('meta_description', models.TextField(default='Site Reliability Engineer specializing in infrastructure, security, and automation. Based in Stockholm, Sweden.', help_text='Default meta description (max 160 characters)', max_length=160)),
                ('meta_keywords', models.CharField(default='SRE, DevOps, Security, Infrastructure, Django, Python, Proxmox', help_text='Default meta keywords (comma-separated)', max_length=255)),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics tracking ID (e.g., G-XXXXXXXXXX)', max_length=50)),
                ('og_image', models.ForeignKey(blank=True, help_text='Default Open Graph image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'SEO Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter/X profile URL')),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('location', models.CharField(default='Stockholm, Sweden', help_text='Your location', max_length=100)),
                ('hackthebox_url', models.URLField(blank=True, help_text='HackTheBox profile URL')),
                ('tryhackme_url', models.URLField(blank=True, help_text='TryHackMe profile URL')),
                ('htb_rank', models.CharField(blank=True, default='Noob', help_text='Your HTB rank (e.g., Hacker, Pro Hacker, Elite)', max_length=50)),
                ('htb_boxes_owned', models.IntegerField(default=0, help_text="Number of boxes you've owned")),
                ('htb_user_owns', models.IntegerField(default=0, help_text='User-owned flags')),
                ('htb_system_owns', models.IntegerField(default=0, help_text='System-owned flags')),
                ('htb_challenges', models.IntegerField(default=0, help_text='Challenges solved')),
                ('footer_text', models.CharField(default='Site Reliability Engineer | Security Enthusiast | HTB Player', help_text='Short bio for footer', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Social Media Settings',
            },
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Project date')),
                ('intro', models.CharField(help_text='Short description', max_length=250)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('archived', 'Archived'), ('ongoing', 'Ongoing')], default='completed', max_length=20)),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL')),
                ('live_url', models.URLField(blank=True, help_text='Live demo URL')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('markdown', 1), ('code', 4), ('image', 7), ('quote', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'template': 'blocks/heading_block.html'}), 1: ('wagtailmarkdown.blocks.MarkdownBlock', (), {'icon': 'pilcrow', 'template': 'blocks/markdown_block.html'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('bash', 'Bash/Shell'), ('html', 'HTML'), ('css', 'CSS'), ('sql', 'SQL'), ('json', 'JSON'), ('yaml', 'YAML'), ('dockerfile', 'Dockerfile')]}), 3: ('wagtail.blocks.TextBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('language', 2), ('code', 3)]], {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6), ('attribution', 6)]], {}), 8: ('wagtail.blocks.StructBlock', [[('quote', 3), ('author', 6)]], {})})),
                ('problem', wagtail.fields.RichTextField(blank=True, help_text='What problem did this solve?')),
                ('solution', wagtail.fields.RichTextField(blank=True, help_text='How did you solve it?')),
                ('duration', models.CharField(blank=True, help_text="e.g. '2 weeks', '3 months'", max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='home.projectcategory')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('tech_stack', models.ManyToManyField(blank=True, related_name='projects', to='home.techstack')),
            ],
            options={
                'verbose_name': 'Project',
                'ordering': ['-date'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
