# Generated by Django 5.1.3 on 2025-11-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='color',
            field=models.CharField(default='#9FEF00', help_text='Hex color code (e.g. #9FEF00)', max_length=7),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='color',
            field=models.CharField(default='#00BAFF', help_text='Hex color code (e.g. #00BAFF)', max_length=7),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji icon', max_length=10),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji icon', max_length=10),
        ),
    ]
