# Generated by Django 5.0.9 on 2025-11-29 23:01

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogcategory_color_projectcategory_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='tech_stack',
        ),
        migrations.CreateModel(
            name='ProjectPageTechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_primary', models.BooleanField(blank=True, default=False)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_stack_items', to='home.projectpage')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.techstack')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
