# Generated by Django 5.2.17 on 2026-09-10 13:59

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepageproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='architecture',
            field=wagtail.fields.RichTextField(blank=True, help_text='System architecture, design and important technical decisions'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='lessons_learned',
            field=wagtail.fields.RichTextField(blank=True, help_text='Important lessons, trade-offs or improvements identified'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='outcome',
            field=wagtail.fields.RichTextField(blank=True, help_text='Result, outcome or current state of the project'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='role',
            field=models.CharField(blank=True, help_text='Your role or responsibility in the project', max_length=120),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='security_considerations',
            field=wagtail.fields.RichTextField(blank=True, help_text='Security considerations, controls, risks and design decisions'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='testing_validation',
            field=wagtail.fields.RichTextField(blank=True, help_text='How the project was tested, validated or verified'),
        ),
    ]
