# Generated by Django 5.2.17 on 2026-09-11 05:46

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_projectpage_case_study'),
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduce the lab and its purpose.')),
                ('overview', wagtail.fields.RichTextField(blank=True, help_text="The environment's purpose and scope.")),
                ('platform_architecture', wagtail.fields.RichTextField(blank=True, help_text='Platform design and architectural decisions.')),
                ('networking', wagtail.fields.RichTextField(blank=True, help_text='Networking principles and design, without private connection details.')),
                ('containerization', wagtail.fields.RichTextField(blank=True, help_text='Workloads, containers and how they are managed.')),
                ('security_controls', wagtail.fields.RichTextField(blank=True, help_text='Security practices and controls suitable for public documentation.')),
                ('operations_recovery', wagtail.fields.RichTextField(blank=True, help_text='Operational practices, validation and recovery approach.')),
                ('current_experiments', wagtail.fields.RichTextField(blank=True, help_text='Current investigations, experiments and learning.')),
                ('hero_image', models.ForeignKey(blank=True, help_text='Optional image or diagram suitable for public viewing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Lab Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
