# Generated by Django 5.2.17 on 2026-09-11 10:11

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_labpage'),
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabEntryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', models.CharField(help_text='Short public summary of the lab or experiment.', max_length=300)),
                ('status', models.CharField(choices=[('active', 'Active'), ('experimenting', 'Experimenting'), ('documented', 'Documented'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('github_url', models.URLField(blank=True, help_text='Optional public repository URL')),
                ('objective', wagtail.fields.RichTextField(blank=True, help_text='What are you trying to build, test or understand?')),
                ('architecture', wagtail.fields.RichTextField(blank=True, help_text='Environment, components and technical design.')),
                ('implementation', wagtail.fields.RichTextField(blank=True, help_text='How the lab was built or configured.')),
                ('security_considerations', wagtail.fields.RichTextField(blank=True, help_text='Security controls, risks, assumptions and boundaries.')),
                ('findings', wagtail.fields.RichTextField(blank=True, help_text='Observations, results, problems discovered or lessons from the lab.')),
                ('next_steps', wagtail.fields.RichTextField(blank=True, help_text='Planned improvements, unanswered questions or future work.')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('markdown', 1), ('code', 4), ('image', 7), ('quote', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'template': 'blocks/heading_block.html'}), 1: ('wagtailmarkdown.blocks.MarkdownBlock', (), {'icon': 'pilcrow', 'template': 'blocks/markdown_block.html'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('bash', 'Bash/Shell'), ('html', 'HTML'), ('css', 'CSS'), ('sql', 'SQL'), ('json', 'JSON'), ('yaml', 'YAML'), ('dockerfile', 'Dockerfile')]}), 3: ('wagtail.blocks.TextBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('language', 2), ('code', 3)]], {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6), ('attribution', 6)]], {}), 8: ('wagtail.blocks.StructBlock', [[('quote', 3), ('author', 6)]], {})})),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Lab Project',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LabEntryPageTechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_primary', models.BooleanField(blank=True, default=False)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_stack_items', to='home.labentrypage')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.techstack')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
