# Generated by Django 5.2.17 on 2026-09-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_lab_entry_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='labentrypage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this entry in the Current Focus section of the Lab index.'),
        ),
        migrations.AddField(
            model_name='labentrypage',
            name='lab_type',
            field=models.CharField(choices=[('infrastructure', 'Infrastructure'), ('security', 'Security'), ('automation', 'Automation'), ('observability', 'Observability'), ('research', 'Research')], default='research', help_text='Primary area for this lab or experiment.', max_length=20),
        ),
    ]
